version: "3.9"
services:
  web:
    image: reservations
    build:
      context: ../../
      dockerfile: src/Reservation.Api/Dockerfile
    ports:
      - "5900:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sql-db-init
      
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=str0ngP@ass
      - MSSQL_PID=Developer
    ports:
      - "1439:1433"
      
  sql-db-init:
    image: krossk/mssql-seed
    environment:
      - MSSQL_HOST_NAME=sql-server
      - SA_PASSWORD=str0ngP@ass
      - DATABASES=Reservations
    depends_on:
      - sql-server